### PR TITLE
remove reference

### PR DESCRIPTION
**Pull request by flavio**
The `Reference` struct has been moved into the oci-spec crate.

This PR removes the duplicated files and exports `Reference` from the oci-spec crate.

Consumers of `oci-client` won't even need the change, unless they were importing `Reference` from `oci_client::reference::Reference` instad of `oci_client::Reference`.

On top of that, I've also addressed some clippy warnings.

### CODE REVIEW

**Comment by flavio** [comment]
CC @cgwalters

**Review by cgwalters — APPROVED** [review]

**Review by Xynnn007 — APPROVED** [review]

**Comment by Xynnn007** [comment]
Hey folks, will a new release be published after this PR gets merged?

**Comment by flavio** [comment]
@thomastaylor312 would you mind giving a quick look at this PR?

@Xynnn007 yes, I think we can do that

**Review by thomastaylor312 — APPROVED** [review]
All good here! Sorry for the delay, got pulled away into other priority work and haven't had time until now to come back. Excited to see us using oci-spec

**Comment by flavio** [comment]
@thomastaylor312 no worries!

**Pull request merged**
